[package]
name = "bzr"
version = "0.1.0"
edition = "2021"
description = "Bzr lang interpreter"
authors = ["Paulo Gabriel Justino Bezerra <pgjbzr@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
